// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { existsSync } from "node:fs";

// The docs pages are generated by scripts/import-docs.mjs from the versioncam
// package as npm publishes it; the sidebar groups the directories it writes.
// `more/` holds README sections the importer has no place for yet, and only
// appears when there are some.
const more = existsSync(new URL("./src/content/docs/more", import.meta.url));

export default defineConfig({
  site: "https://version.cam",
  integrations: [
    starlight({
      title: "Versioncam",
      description:
        "Record demo clips of a real web app: scripted, deterministic, regenerated on deploy.",
      favicon: "/favicon.svg",
      social: [
        {
          icon: "github",
          label: "Issues",
          href: "https://github.com/versioncam/versioncam",
        },
      ],
      customCss: ["./src/styles/site.css"],
      sidebar: [
        { label: "Start", items: [{ autogenerate: { directory: "start" } }] },
        {
          label: "Reference",
          items: [{ autogenerate: { directory: "reference" } }],
        },
        {
          label: "How it works",
          items: [{ autogenerate: { directory: "how-it-works" } }],
        },
        ...(more
          ? [{ label: "More", items: [{ autogenerate: { directory: "more" } }] }]
          : []),
        { label: "About", items: [{ autogenerate: { directory: "about" } }] },
      ],
    }),
  ],
});
